[env:scanner_node]
platform    = espressif32
board       = heltec_wifi_lora_32_V4
framework   = arduino

build_flags =
    -DCORE_DEBUG_LEVEL=0          ; suppress IDF noise on serial in PCAP mode

lib_deps =
    jgromes/RadioLib@^6.6.0
    rweather/Crypto@^0.4.0
    bblanchon/ArduinoJson@^7.1.0
    adafruit/Adafruit SSD1306@^2.5.9
    adafruit/Adafruit GFX Library@^1.11.9
    adafruit/Adafruit BusIO@^1.14.0
